### ISSUE TITLE
runtime error in Frame1 with toString

### ISSUE THREAD

**Issue by Wladefant** [RealEst-AI/ImmoMail-Outlook-Addin#63]
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'toString')
TypeError: Cannot read properties of undefined (reading 'toString')
    at eval (webpack-internal:///./components/Frame1.tsx:736:51)
    at step (webpack-internal:///./components/Frame1.tsx:67:23)
    at Object.eval [as next] (webpack-internal:///./components/Frame1.tsx:48:53)
    at fulfilled (webpack-internal:///./components/Frame1.tsx:39:58

**Comment by Wladefant** [comment]
fixed with https://github.com/RealEst-AI/ImmoMail-Outlook-Addin/commit/afd37afda0234ff805badc407de952bc0ff845d9
